#!/usr/bin/env sh
set -ex

PLATFORM=$(uname -s | awk '{print tolower($0)}')

./node_modules/.bin/pkg \
  ./bin/michaelhost.js \
  --target host \
  --public \
  --output ./distapp/assets/michaelhost_bin.asset \
  --config ./package.json
cp ./node_modules/node-pty/build/Release/pty.node ./distapp/assets/pty.node.asset

./node_modules/.bin/pkg \
  ./distapp/entrypoint.js \
  --target host \
  --public \
  --output ./dist/michaelhost-${PLATFORM} \
  --config ./distapp/package.json
