name: "michaelhost push"
description: "push an image update to michaelhost webhook"
inputs:
  michaelhost_webhook_url:
    description: public URL of michaelhost webhook server
    required: true
  michaelhost_secret:
    description: michaelhost secret
    required: true
  image_name:
    description: image name
    required: true
  image_tag:
    description: image tag
    required: true
    default: latest
runs:
  using: "docker"
  image: "Dockerfile"
