name: build

on:
  push:
    branches:
      - "*"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: "echo $GITHUB_SHA > REVISION"
      - run: yarn install
      - run: yarn install
        working-directory: admin_ui
      - run: yarn build
      - uses: actions/upload-artifact@v1
        with:
          name: michaelhost-linux
          path: "dist"
