name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish_to_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: npm
      - run: "echo $GITHUB_SHA > REVISION"
      - run: npm install
      - run: npm install
        working-directory: admin_ui
      - run: npm run build
      - run: npm publish --provenance
