name: release

on:
  push:
    tags:
      - "v*"
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: "echo $GITHUB_SHA > REVISION"
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: michaelhost-linux
          path: "dist/"
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: "build/"
  publish_to_npm:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: "build/"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish_to_github:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: michaelhost-linux
          path: "dist/"

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: michaelhost-darwin
          asset_path: ./dist/michaelhost-darwin
          asset_content_type: application/octet-stream
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: michaelhost-linux
          asset_path: ./dist/michaelhost-linux
          asset_content_type: application/octet-stream
      - uses: rollbar/github-deploy-action@1.1.0
        with:
          environment: 'production'
          version: ${{ github.sha }}
        env:
          ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
          ROLLBAR_USERNAME: ${{ github.actor }}
